### PR TITLE
subscribe and unsubscribe in sport and profile

### PR DESCRIPTION
**Pull request by Tharunthorn**

### CODE REVIEW

**Review by teenteennnii — CHANGES_REQUESTED** [review]
- In Sport detail, i'm not sure is it correctly or my machine not load CSS
Screenshot 2566-11-21 at 19 04 59

- In Home after subscribe why 8-11 don't have table.
Screenshot 2566-11-21 at 19 04 43

- In Profile, I think it should center of the page
Screenshot 2566-11-21 at 19 13 04

- Please fix picture of some sports.
1. 
Screenshot 2566-11-21 at 19 06 39
=> 
Screenshot 2566-11-21 at 19 07 06

2. 
Screenshot 2566-11-21 at 19 06 45
=> 
Screenshot 2566-11-21 at 19 06 59

3.
Screenshot 2566-11-21 at 19 18 21
=>
Screenshot 2566-11-21 at 19 18 27

**Comment by teenteennnii** [comment]
And in my opinion, I think when the user clicks subscribe it takes very long time. It will be good if you add something to let users know that our website is still loading.

**Comment by Tharunthorn** [comment]
Hmm that weird

**Comment by teenteennnii** [comment]
I cannot see the photo

**Pull request closed without merging**
